services:
  react-chat:
    build:
      context: .
      args:
        VITE_BACKEND_URL: mongodb://root:example@mongo:27017/chat
      ports:
        - "30000:80"
        - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - chat-network
network:
  chat-network:
    driver: bridge
