name: Docker CI/CD

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Log in to Docker Hub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Remove old local image
      - name: Remove old local image
        run: docker rmi -f devjam12/c-frontend:latest || true

      # 4. Build new Docker image
      - name: Build Docker image
        run: docker build --build-arg VITE_BACKEND_URL=${{ secrets.VITE_BACKEND_URL }}-t devjam12/c-frontend:latest .

      # 5. Push Docker image to Docker Hub
      - name: Push Docker image
        run: docker push devjam12/c-frontend:latest

      # 6. Deploy to EC2
      # - name: Deploy to EC2
      #   uses: appleboy/ssh-action@v0.1.7
      #   with:
      #     host: ${{ secrets.EC2_HOST }}
      #     username: ubuntu
      #     key: ${{ secrets.EC2_SSH_KEY }}
      #     script: |
      #       # Stop & remove existing node container
      #       docker stop node-app || true
      #       docker rm node-app || true

      #       # Run Node app container
      #       docker run -d \
      #         --name node-app \
      #         -p 3000:3000 \
      #         devjam12/node-server:latest
      # - name: Test SSH connection
      #   uses: appleboy/ssh-action@v0.1.7
      #   with:
      #     host: ${{ secrets.EC2_HOST }}
      #     username: ubuntu
      #     key: ${{ secrets.EC2_SSH_KEY }}
      #     port: 22
      #     script: |
      #       echo "SSH connection successful"
      #       whoami
      #       hostname
